name: Terraform Deploy

on:
  push:
    branches:
      - master
jobs:
  terraform:
    name: Deploy with Terraform
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure AWS credentials using secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform  # Point to the terraform directory

      # Validate the Terraform configuration
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform  # Point to the terraform directory

      # Plan the Terraform deployment
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform  # Point to the terraform directory

      # Apply the Terraform configuration (auto-approve to avoid prompt)
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform  # Point to the terraform directory

  ansible:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Configure AWS credentials using secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform  # Point to the terraform directory

      - name: Get Terraform Output
        id: terraform
        run: echo "INSTANCE_IP=$(terraform output -raw instance_public_ip | tr -d '\n')" >> $GITHUB_ENV
        #run: INSTANCE_IP=echo"$(terraform output -raw instance_public_ip)"

      - name: Use the INSTANCE_IP variable
        run: echo "Instance IP is $INSTANCE_IP"

      - name: Set up Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install ansible

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i "$INSTANCE_IP," ansible/playbook.yml
        env:
          ANSIBLE_SSH_USER: ubuntu  # Adjust according to your SSH user
          ANSIBLE_SSH_PRIVATE_KEY: ${{ secrets.SSHKEY }}
