name: Terraform Destroy

on:
  workflow_dispatch:  # Allows you to trigger the workflow manually from the GitHub UI

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    steps:
      # Clone and checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      # Install and set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6 

      # Initialize Terraform (if you are using a remote backend)
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform  # Ajusta según la estructura de tu directorio

      # Destroy Terraform infrastructure
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./terraform 
