name: Terraform Destroy

on:
  workflow_dispatch:  # Permite disparar el workflow manualmente desde la UI de GitHub

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    steps:
      # Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configura las credenciales de AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Especifica tu región de AWS

      # Configura Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6  # Especifica la versión de Terraform que estás usando

      # Inicializa Terraform (si estás usando un backend remoto)
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform  # Ajusta según la estructura de tu directorio

      # Destruye la infraestructura de Terraform
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./terraform  # Ajusta según la estructura de tu directorio
